name:  "GivTCP-DEV"
description:  "TCP Modbus connection to MQTT/JSON for Givenergy Battery/PV Invertors"
version:  "3.4.15"
image: givtcp.docker.scarf.sh/britkat/giv_tcp-dev
slug:  "givtcp-dev"
homeassistant_api: true
hassio_api: true
init:  true
ingress: true
services:
  - "mqtt:want"
map:
  - config:rw
  - ssl
boot:  auto
url:  https://github.com/britkat1980/giv_tcp
legacy:  true
arch: 
  - aarch64
  - amd64
host_network: true
